01-basics 01-CounterButton 02-MeetupPageDraft
js-tasks-ru/vue-20200925-2_tatyana179 pull request #1
Opened 2020-10-13 08:05 UTC by Omletina

2020-10-13 08:12 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-13 20:25 UTC, ShGKme requested changes
Задача CounterButton принята.

В задаче MeetupsPageDraft требуется исправить XSS...

2020-10-13 20:25 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title" v-html="item.title"></h5>
v-html выведет значение как html без какого-либо экранирования. Это потенциальный XSS.

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С v-html получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

Если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/). `All you need is <s>love</s> Apollo Client`

Но наличие таких названий не должно приводить к XSS

2020-10-15 15:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Сумма двух чисел
+ Функция sum быть определена
- Функция sum должна получать 1+1=2
- Функция sum должна получать 10+20=30
- Функция sum должна получать 0+0=0
- Функция sum должна получать -2+(-1)=-3
```
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

2020-10-15 15:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-15 16:59 UTC, ShGKme approved these changes
Все задачи приняты 👍

2020-10-15 17:00 UTC, merged